/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { EntityModelHost } from './entityModelHost';

export type _PagedModelEntityModelHostEmbedded = {
  hosts?: EntityModelHost[];
};
