/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { Links } from './links';

export interface EntityModelHost {
  _links?: Links;
  date?: string;
  hw?: string;
  /** @pattern ^(?:[0-9]{1,3}\.){3}[0-9]{1,3}$ */
  ip?: string;
  known?: boolean;
  /** @pattern ^([0-9A-Fa-f]{2}[:-]){5}([0-9A-Fa-f]{2})$ */
  mac?: string;
  name: string;
  now?: boolean;
}
