/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export * from './_pagedModelEntityModelHostEmbedded';
export * from './abstractJsonSchemaPropertyObject';
export * from './entityModelHost';
export * from './getCollectionResourceHostGetParams';
export * from './hostRequestBody';
export * from './item';
export * from './itemProperties';
export * from './jsonSchema';
export * from './jsonSchemaDefinitions';
export * from './jsonSchemaProperties';
export * from './link';
export * from './links';
export * from './pageMetadata';
export * from './pagedModelEntityModelHost';
export * from './representationModelObject';
