/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { ItemProperties } from './itemProperties';

export interface Item {
  properties?: ItemProperties;
  requiredProperties?: string[];
  type?: string;
}
