/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { Item } from './item';

export type JsonSchemaDefinitions = { [key: string]: Item };
