/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { _PagedModelEntityModelHostEmbedded } from './_pagedModelEntityModelHostEmbedded';
import type { Links } from './links';
import type { PageMetadata } from './pageMetadata';

export interface PagedModelEntityModelHost {
  _embedded?: _PagedModelEntityModelHostEmbedded;
  _links?: Links;
  page?: PageMetadata;
}
