/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import { HttpClient } from '@angular/common/http';
import type {
  HttpContext,
  HttpEvent,
  HttpHeaders,
  HttpParams,
  HttpResponse as AngularHttpResponse,
} from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import type { JsonSchema, RepresentationModelObject } from '../../models';

type HttpClientOptions = {
  headers?:
    | HttpHeaders
    | {
        [header: string]: string | string[];
      };
  context?: HttpContext;
  observe?: any;
  params?:
    | HttpParams
    | {
        [param: string]:
          | string
          | number
          | boolean
          | ReadonlyArray<string | number | boolean>;
      };
  reportProgress?: boolean;
  responseType?: any;
  withCredentials?: boolean;
};

@Injectable({ providedIn: 'root' })
export class ProfileControllerService {
  constructor(private http: HttpClient) {}
  listAllFormsOfMetadata<TData = RepresentationModelObject>(
    options?: Omit<HttpClientOptions, 'observe'> & { observe?: 'body' }
  ): Observable<TData>;
  listAllFormsOfMetadata<TData = RepresentationModelObject>(
    options?: Omit<HttpClientOptions, 'observe'> & { observe?: 'response' }
  ): Observable<AngularHttpResponse<TData>>;
  listAllFormsOfMetadata<TData = RepresentationModelObject>(
    options?: Omit<HttpClientOptions, 'observe'> & { observe?: 'events' }
  ): Observable<HttpEvent<TData>>;
  listAllFormsOfMetadata<TData = RepresentationModelObject>(
    options?: HttpClientOptions
  ): Observable<TData> {
    return this.http.get<TData>(`/profile`, options);
  }
  descriptor<TData = string | JsonSchema>(
    options?: Omit<HttpClientOptions, 'observe'> & { observe?: 'body' }
  ): Observable<TData>;
  descriptor<TData = string | JsonSchema>(
    options?: Omit<HttpClientOptions, 'observe'> & { observe?: 'response' }
  ): Observable<AngularHttpResponse<TData>>;
  descriptor<TData = string | JsonSchema>(
    options?: Omit<HttpClientOptions, 'observe'> & { observe?: 'events' }
  ): Observable<HttpEvent<TData>>;
  descriptor<TData = string | JsonSchema>(
    options?: HttpClientOptions
  ): Observable<TData> {
    return this.http.get<TData>(`/profile/hosts`, options);
  }
}

export type ListAllFormsOfMetadataClientResult =
  NonNullable<RepresentationModelObject>;
export type DescriptorClientResult = NonNullable<string | JsonSchema>;
